### ISSUE TITLE
Error iniciando el shard 0

### ISSUE THREAD

**Issue by NoSoyDany** [LyricalString/Node-Discord-Bot#20]
Aún hechos los pasos, la consola tira el siguiente error al ejecutar `npm start`.

(Hosteado en replit.com)

`Iniciando shard 0
(node:56) DeprecationWarning: The message sweeping client options are deprecated, use the makeCache option with LimitedCollection instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Error: ENOTDIR: not a directory, scandir './commands/.env'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: './commands/.env'
}
[Error: ENOTDIR: not a directory, scandir './commands/.gitattributes'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: './commands/.gitattributes'
}
[Error: ENOTDIR: not a directory, scandir './commands/.gitignore'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: './commands/.gitignore'
}
[Error: ENOTDIR: not a directory, scandir './commands/application.yml'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: './commands/application.yml'
}
node:internal/modules/cjs/loader:940
  const err = new Error(message);
              ^

Error: Cannot find module '.././lang/index.json'
Require stack:
- /home/runner/SphericalFaroffIntroductory/commands/structures/Client.js
- /home/runner/SphericalFaroffIntroductory/handlers/commands.js
- /home/runner/SphericalFaroffIntroductory/bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/runner/SphericalFaroffIntroductory/commands/structures/Client.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at iniciar (/home/runner/SphericalFaroffIntroductory/handlers/commands.js:13:21)
    at /home/runner/SphericalFaroffIntroductory/handlers/commands.js:23:7
    at FSReqCallback.oncomplete (node:fs:184:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/SphericalFaroffIntroductory/commands/structures/Client.js',
    '/home/runner/SphericalFaroffIntroductory/handlers/commands.js',
    '/home/runner/SphericalFaroffIntroductory/bot.js'
  ]
}
Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/SphericalFaroffIntroductory/node_modules/discord.js/src/sharding/Shard.js:160:16)
    at Object.onceWrapper (node:events:472:26)
    at Shard.emit (node:events:365:28)
    at Shard._handleExit (/home/runner/SphericalFaroffIntroductory/node_modules/discord.js/src/sharding/Shard.js:392:10)
    at ChildProcess.emit (node:events:365:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  [Symbol(code)]: 'SHARDING_READY_DIED'
}`

**Comment by NoSoyDany** [comment]
Versión de node: v16.0.0
Versión de NPM: v6.14.15

**Comment by aarons124** [comment]
1. Revisa tus options del cliente.
2. El directorio `.././lang/index.json` no fue encontrado, tienes que especificar correctamente el directorio si es que existe.

**Comment by eliyya** [comment]
yo veo mucho el `/commands/`, me hace creer que tu estructura en replit esta mal montada, no deberia haber nada dentro de `/commands/` mas que carpetas con comandos, el error dice `not a directory`, ya que espera encontrar carpetas ahi, no archivos. prueba crear otro replit clonando el repositorio

**Comment by eliyya** [comment]
Lograste resolver el problema?
recomiendo cerrar el issue si es asi
