### ISSUE TITLE
Error ao iniciar play 

### ISSUE THREAD

**Issue by DiogenesYazan** [LyricalString/Node-Discord-Bot#28]
Cada vez que le doy al comando play (música) da error. incluso con lavalink2 abierto.

error:
RangeError: No available nodes.

error completo:

play [413096238142062592] [853855291912880140]
RangeError: No available nodes.
    at new Player (D:[PROJETOS]\node.js\YazanTheBot\node_modules\erela.js\dist\structures\Player.js:82:19)
    at Manager.create (D:[PROJETOS]\node.js\YazanTheBot\node_modules\erela.js\dist\structures\Manager.js:205:16) 
    at Play.run (D:[PROJETOS]\node.js\YazanTheBot\commands\Musica\play.js:60:43)
    at commandRun (D:[PROJETOS]\node.js\YazanTheBot\events\clients\messageCreate.js:1390:33)
    at messageCreate.run (D:[PROJETOS]\node.js\YazanTheBot\events\clients\messageCreate.js:187:17)
    at module.exports.<anonymous> (D:[PROJETOS]\node.js\YazanTheBot\handlers\events.js:16:48)
    at module.exports.emit (node:events:526:28)
    at MessageCreateAction.handle (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\client\actions\MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^
[13:20]
DiscordAPIError: Invalid Form Body
webhook_id: Value "id del webhook donde se enviarán los errores" is not snowflake.
    at RequestHandler.execute (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async WebhookClient.send (D:[PROJETOS]\node.js\YazanTheBot\node_modules\discord.js\src\structures\Webhook.js:196:15) {
  method: 'post',
  path: '/webhooks/id del webhook donde se enviarán los errores/token del webhook donde se enviarán los errores?wait=true',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: 'Ocorreu um erro em Sv My coisitas [ID Server: 853855291912885000] [ID Usuario: 413096238150402592] [Owner: 413096238150402592]. Numero de usuarios: 3\n' +
        'Mensagem: $play dojacat\n' +
        '\n' +
        'Error: RangeError: No available nodes.\n' +
        '\n' +
        '------------------------------------',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Comment by DiogenesYazan** [comment]
resolvido:
Basta baixar a versão mais recente do lavalink e em applications.yml na source escrever true no youtube
